import "./globals.css";

export const metadata = {
    title: "ProcaDoro",
    description: "Generated by Jeiku's Development",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-customColor60 font-poppins">{children}</body>
        </html>
    );
}
